(source_file) @source
(expression) @expr
(function_call) @call
(argument_list) @args
(binary_expression) @binary
(unary_expression) @unary
(parenthesized_expression) @parens
(column_reference) @column_ref
(literal) @literal
(number) @number
(string) @string
(boolean) @bool
(null) @null
(identifier) @id
(column_name) @colname
(lambda_expression) @lambda
(lambda_body) @lambda_body
(lambda_binary_expression) @lambda_binary
(lambda_unary_expression) @lambda_unary
(lambda_parenthesized_expression) @lambda_parens
(parameter_list) @param_list
